### ISSUE TITLE
Rock needs the option to Install VMWare Harbor

### ISSUE THREAD

**Issue by grantcurell** [grantcurell/rock#13]
As part of the move to containers, VMWare Harbor can provide a good front end registry. The Rock installer should have the option to install this software, but it should be optional and controlled in playbooks/vars/rocknsm_config.dist.yml. Once installed, Harbor should be controlled by a service.

Here is the existing code that installed Harbor:

[070_dockervm_pull-configure_harbor.sh.txt](https://github.com/rocknsm/rock/files/1552017/070_dockervm_pull-configure_harbor.sh.txt)

Existing service file:
[harbor.service.txt](https://github.com/rocknsm/rock/files/1552022/harbor.service.txt)

**Comment by grantcurell** [comment]
duckmanjbr is working on this one - feel free to hit him up to work on it with him.

**Comment by Duckmanjbr** [comment]
Harbor role added.
